// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtrbbilhtkzsmveiyfal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0cmJiaWxodGt6c212ZWl5ZmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NDExMjgsImV4cCI6MjA4NDQxNzEyOH0.33mHg1N0dnc8y25_zAfs-gawhXsR3tlND0JdysfcjcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});